version: "3"

networks:
  dnscrypt_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24

services:
  dnscrypt-proxy:
    container_name: dnscrypt-proxy
    image: klutchell/dnscrypt-proxy:latest
    user: nobody
    networks:
      dnscrypt_net:
        ipv4_address: 172.18.0.2
    expose:
      - "53/udp"
      - "53/tcp"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "./dnscrypt-proxy.toml:/config/dnscrypt-proxy.toml"
    restart: unless-stopped
